const DOM={menuBtn:document.getElementById("menuBtn"),mobileDrawer:document.getElementById("mobileDrawer"),locateBtn:document.getElementById("locateBtn"),drawerLocateBtn:document.getElementById("drawerLocateBtn"),statusLabel:document.getElementById("statusLabel"),locationLabel:document.getElementById("locationLabel"),currentTime:document.getElementById("currentTime"),lastUpdatedLabel:document.getElementById("lastUpdatedLabel"),heroDayLabel:document.getElementById("heroDayLabel"),heroTemp:document.getElementById("heroTemp"),heroWeatherText:document.getElementById("heroWeatherText"),heroRate:document.getElementById("heroRate"),heroNewsCount:document.getElementById("heroNewsCount"),heroNewsText:document.getElementById("heroNewsText"),heroWalletBalance:document.getElementById("heroWalletBalance"),heroWalletText:document.getElementById("heroWalletText"),weatherTemp:document.getElementById("weatherTemp"),weatherCondition:document.getElementById("weatherCondition"),feelsLike:document.getElementById("feelsLike"),windSpeed:document.getElementById("windSpeed"),weatherCodeLabel:document.getElementById("weatherCodeLabel"),forecastStrip:document.getElementById("forecastStrip"),usdToDop:document.getElementById("usdToDop"),eurToDop:document.getElementById("eurToDop"),exchangeUpdated:document.getElementById("exchangeUpdated"),routeForm:document.getElementById("routeForm"),originInput:document.getElementById("originInput"),destinationInput:document.getElementById("destinationInput"),routeSummary:document.getElementById("routeSummary"),mapStatus:document.getElementById("mapStatus"),newsQuery:document.getElementById("newsQuery"),searchNewsBtn:document.getElementById("searchNewsBtn"),newsList:document.getElementById("newsList"),incomeForm:document.getElementById("incomeForm"),salaryInput:document.getElementById("salaryInput"),incomeValue:document.getElementById("incomeValue"),expenseValue:document.getElementById("expenseValue"),balanceValue:document.getElementById("balanceValue"),walletStatusValue:document.getElementById("walletStatusValue"),budgetPercentLabel:document.getElementById("budgetPercentLabel"),budgetProgress:document.getElementById("budgetProgress"),expenseForm:document.getElementById("expenseForm"),expenseTitle:document.getElementById("expenseTitle"),expenseAmount:document.getElementById("expenseAmount"),expenseCategory:document.getElementById("expenseCategory"),expensesList:document.getElementById("expensesList"),clearExpensesBtn:document.getElementById("clearExpensesBtn")};
const STORAGE_KEYS={coords:"brinow_coords",locationName:"brinow_location_name",salary:"brinow_salary",expenses:"brinow_expenses"};
const FALLBACK_LOCATION={lat:18.4861,lon:-69.9312,name:"Santo Domingo, RD"};
const state={coords:loadCoords(),locationName:localStorage.getItem(STORAGE_KEYS.locationName)||FALLBACK_LOCATION.name,map:null,userMarker:null,routeLine:null,salary:Number(localStorage.getItem(STORAGE_KEYS.salary)||0),expenses:loadExpenses()};
document.addEventListener("DOMContentLoaded",init);
function init(){bindEvents();initClock();initMap();updateLocationLabel(state.locationName);renderWallet();refreshAll()}
function bindEvents(){
if(DOM.menuBtn){DOM.menuBtn.addEventListener("click",()=>DOM.mobileDrawer.classList.toggle("open"))}
if(DOM.locateBtn){DOM.locateBtn.addEventListener("click",detectUserLocation)}
if(DOM.drawerLocateBtn){DOM.drawerLocateBtn.addEventListener("click",detectUserLocation)}
if(DOM.searchNewsBtn){DOM.searchNewsBtn.addEventListener("click",()=>loadNews(DOM.newsQuery.value.trim()||"República Dominicana"))}
if(DOM.routeForm){DOM.routeForm.addEventListener("submit",async e=>{e.preventDefault();await calculateRoute()})}
if(DOM.incomeForm){DOM.incomeForm.addEventListener("submit",e=>{e.preventDefault();const salary=Number(DOM.salaryInput.value);if(!Number.isFinite(salary)||salary<0)return;state.salary=salary;localStorage.setItem(STORAGE_KEYS.salary,String(salary));renderWallet();setStatus("Sueldo guardado")})}
if(DOM.expenseForm){DOM.expenseForm.addEventListener("submit",e=>{e.preventDefault();const title=DOM.expenseTitle.value.trim();const amount=Number(DOM.expenseAmount.value);const category=DOM.expenseCategory.value;if(!title||!Number.isFinite(amount)||amount<=0)return;state.expenses.unshift({id:cryptoRandomId(),title,amount,category,createdAt:new Date().toISOString()});persistExpenses();DOM.expenseTitle.value="";DOM.expenseAmount.value="";DOM.expenseCategory.value="Hogar";renderWallet();setStatus("Gasto agregado")})}
if(DOM.clearExpensesBtn){DOM.clearExpensesBtn.addEventListener("click",()=>{state.expenses=[];persistExpenses();renderWallet();setStatus("Gastos eliminados")})}
if(DOM.expensesList){DOM.expensesList.addEventListener("click",e=>{const button=e.target.closest("[data-expense-id]");if(!button)return;const id=button.getAttribute("data-expense-id");state.expenses=state.expenses.filter(expense=>expense.id!==id);persistExpenses();renderWallet();setStatus("Gasto eliminado")})}}
function initClock(){const formatter=new Intl.DateTimeFormat("es-DO",{hour:"2-digit",minute:"2-digit"});const weekdayFormatter=new Intl.DateTimeFormat("es-DO",{weekday:"long"});function tick(){const now=new Date();DOM.currentTime.textContent=formatter.format(now);DOM.heroDayLabel.textContent=capitalize(weekdayFormatter.format(now))}tick();setInterval(tick,1000)}
async function refreshAll(){setStatus("Actualizando");await Promise.allSettled([loadWeather(),loadExchangeRates(),loadNews("República Dominicana")]);updateMapPosition(state.coords.lat,state.coords.lon,state.locationName);stampUpdated();setStatus("Listo")}
function loadCoords(){const raw=localStorage.getItem(STORAGE_KEYS.coords);if(!raw)return{lat:FALLBACK_LOCATION.lat,lon:FALLBACK_LOCATION.lon};try{const parsed=JSON.parse(raw);if(typeof parsed.lat==="number"&&typeof parsed.lon==="number")return parsed}catch{}return{lat:FALLBACK_LOCATION.lat,lon:FALLBACK_LOCATION.lon}}
function saveCoords(lat,lon){state.coords={lat,lon};localStorage.setItem(STORAGE_KEYS.coords,JSON.stringify(state.coords))}
function loadExpenses(){const raw=localStorage.getItem(STORAGE_KEYS.expenses);if(!raw)return[];try{const parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed:[]}catch{return[]}}
function persistExpenses(){localStorage.setItem(STORAGE_KEYS.expenses,JSON.stringify(state.expenses))}
function updateLocationLabel(name){state.locationName=name;localStorage.setItem(STORAGE_KEYS.locationName,name);DOM.locationLabel.textContent=name}
function stampUpdated(){DOM.lastUpdatedLabel.textContent=new Intl.DateTimeFormat("es-DO",{hour:"2-digit",minute:"2-digit"}).format(new Date())}
function setStatus(text){DOM.statusLabel.textContent=text}
async function detectUserLocation(){if(!navigator.geolocation){setStatus("Ubicación no disponible");return}setStatus("Detectando ubicación");navigator.geolocation.getCurrentPosition(async position=>{const {latitude,longitude}=position.coords;saveCoords(latitude,longitude);await reverseGeocode(latitude,longitude);updateMapPosition(latitude,longitude,state.locationName);await refreshAll()},()=>setStatus("Permiso denegado"),{enableHighAccuracy:true,timeout:12000,maximumAge:0})}
async function reverseGeocode(lat,lon){try{const response=await fetch(`https://nominatim.openstreetmap.org/reverse?lat=${lat}&lon=${lon}&format=json&accept-language=es`);const data=await response.json();const a=data.address||{};const city=a.city||a.town||a.village||a.municipality||"Ubicación actual";const country=a.country||"República Dominicana";updateLocationLabel(`${city}, ${country}`)}catch{updateLocationLabel("Ubicación actual")}}
function weatherLabelFromCode(code){const map={0:"Despejado",1:"Mayormente despejado",2:"Parcialmente nublado",3:"Nublado",45:"Niebla",48:"Niebla helada",51:"Llovizna ligera",53:"Llovizna",55:"Llovizna intensa",61:"Lluvia ligera",63:"Lluvia",65:"Lluvia fuerte",71:"Nieve ligera",73:"Nieve",75:"Nieve fuerte",80:"Chubascos ligeros",81:"Chubascos",82:"Chubascos fuertes",95:"Tormenta"};return map[code]||"Tiempo actual"}
async function loadWeather(){try{const {lat,lon}=state.coords;const response=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,apparent_temperature,wind_speed_10m,weather_code&hourly=temperature_2m,weather_code&forecast_days=2&timezone=auto`);if(!response.ok)throw new Error("weather");const data=await response.json();const c=data.current;const weatherText=weatherLabelFromCode(c.weather_code);DOM.weatherTemp.textContent=`${Math.round(c.temperature_2m)}°C`;DOM.weatherCondition.textContent=weatherText;DOM.feelsLike.textContent=`${Math.round(c.apparent_temperature)}°C`;DOM.windSpeed.textContent=`${Math.round(c.wind_speed_10m)} km/h`;DOM.weatherCodeLabel.textContent=String(c.weather_code);DOM.heroTemp.textContent=`${Math.round(c.temperature_2m)}°`;DOM.heroWeatherText.textContent=weatherText;const hours=(data.hourly.time||[]).slice(0,6).map((time,index)=>({time,temperature:data.hourly.temperature_2m[index],weatherCode:data.hourly.weather_code[index]}));DOM.forecastStrip.innerHTML=hours.map(item=>`<div class="forecast-item"><span class="hour">${new Date(item.time).toLocaleTimeString("es-DO",{hour:"2-digit",minute:"2-digit"})}</span><span class="temp">${Math.round(item.temperature)}°</span><span class="desc">${weatherLabelFromCode(item.weatherCode)}</span></div>`).join("")}catch{DOM.weatherTemp.textContent="--°C";DOM.weatherCondition.textContent="No se pudo cargar el clima";DOM.feelsLike.textContent="--°C";DOM.windSpeed.textContent="-- km/h";DOM.weatherCodeLabel.textContent="--";DOM.heroTemp.textContent="--°";DOM.heroWeatherText.textContent="Sin clima";DOM.forecastStrip.innerHTML=`<div class="empty-state">No se pudo cargar el pronóstico.</div>`}}
async function loadExchangeRates(){try{const [usdResponse,eurResponse]=await Promise.all([fetch("https://open.er-api.com/v6/latest/USD"),fetch("https://open.er-api.com/v6/latest/EUR")]);if(!usdResponse.ok||!eurResponse.ok)throw new Error("fx");const usdData=await usdResponse.json();const eurData=await eurResponse.json();const usdToDop=usdData?.rates?.DOP;const eurToDop=eurData?.rates?.DOP;DOM.usdToDop.textContent=usdToDop?formatMoney(usdToDop):"--";DOM.eurToDop.textContent=eurToDop?formatMoney(eurToDop):"--";DOM.exchangeUpdated.textContent=new Intl.DateTimeFormat("es-DO",{hour:"2-digit",minute:"2-digit"}).format(new Date());DOM.heroRate.textContent=usdToDop?formatMoney(usdToDop):"--"}catch{DOM.usdToDop.textContent="--";DOM.eurToDop.textContent="--";DOM.exchangeUpdated.textContent="Sin conexión";DOM.heroRate.textContent="--"}}
async function loadNews(query){try{DOM.newsList.innerHTML=`<div class="empty-state">Cargando noticias...</div>`;const feedUrl=`https://news.google.com/rss/search?q=${encodeURIComponent(query)}&hl=es-419&gl=DO&ceid=DO:es-419`;const proxyUrl=`https://api.allorigins.win/raw?url=${encodeURIComponent(feedUrl)}`;const response=await fetch(proxyUrl);if(!response.ok)throw new Error("news");const xmlText=await response.text();const parser=new DOMParser();const xml=parser.parseFromString(xmlText,"text/xml");const items=Array.from(xml.querySelectorAll("item")).slice(0,6);if(!items.length){DOM.newsList.innerHTML=`<div class="empty-state">No se encontraron noticias para esa búsqueda.</div>`;DOM.heroNewsCount.textContent="0";DOM.heroNewsText.textContent="Sin resultados";return}const articles=items.map(item=>({title:item.querySelector("title")?.textContent||"Sin título",link:item.querySelector("link")?.textContent||"#",pubDate:item.querySelector("pubDate")?.textContent||"",source:item.querySelector("source")?.textContent||"Fuente",image:`https://picsum.photos/seed/${encodeURIComponent(item.querySelector("title")?.textContent||Math.random())}/400/300`}));DOM.newsList.innerHTML=articles.map(article=>`<article class="news-item"><img src="${article.image}" alt="Noticia"><div class="news-content"><h4>${escapeHtml(article.title)}</h4><p>${escapeHtml(article.source)} · ${escapeHtml(formatNewsDate(article.pubDate))}</p><a href="${article.link}" target="_blank" rel="noopener noreferrer">Ver noticia</a></div></article>`).join("");DOM.heroNewsCount.textContent=String(articles.length);DOM.heroNewsText.textContent=query}catch{DOM.newsList.innerHTML=`<div class="empty-state">No se pudieron cargar las noticias ahora mismo.</div>`;DOM.heroNewsCount.textContent="0";DOM.heroNewsText.textContent="Error"}}
function initMap(){const {lat,lon}=state.coords;state.map=L.map("map",{zoomControl:true}).setView([lat,lon],12);L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{attribution:"&copy; OpenStreetMap &copy; CARTO"}).addTo(state.map);state.userMarker=L.marker([lat,lon]).addTo(state.map);state.userMarker.bindPopup(`<strong>${escapeHtml(state.locationName)}</strong>`)}
function updateMapPosition(lat,lon,label){if(!state.map)return;state.map.setView([lat,lon],12);if(state.userMarker){state.userMarker.setLatLng([lat,lon]);state.userMarker.bindPopup(`<strong>${escapeHtml(label)}</strong>`)}DOM.mapStatus.textContent=`Vista centrada en ${label}.`}
async function geocodeLocation(query){const response=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&accept-language=es&q=${encodeURIComponent(query)}`);if(!response.ok)throw new Error("geo");const data=await response.json();if(!Array.isArray(data)||!data.length)throw new Error("geo");return{lat:Number(data[0].lat),lon:Number(data[0].lon),name:data[0].display_name}}
async function calculateRoute(){const originText=DOM.originInput.value.trim();const destinationText=DOM.destinationInput.value.trim();if(!originText||!destinationText){DOM.routeSummary.textContent="Debes escribir origen y destino.";return}try{DOM.routeSummary.textContent="Calculando ruta...";const origin=await geocodeLocation(originText);const destination=await geocodeLocation(destinationText);const response=await fetch(`https://router.project-osrm.org/route/v1/driving/${origin.lon},${origin.lat};${destination.lon},${destination.lat}?overview=full&geometries=geojson`);if(!response.ok)throw new Error("route");const data=await response.json();const route=data.routes?.[0];if(!route)throw new Error("route");drawRoute(route.geometry.coordinates);DOM.routeSummary.textContent=`Ruta estimada: ${(route.distance/1000).toFixed(1)} km · ${Math.round(route.duration/60)} min aprox.`;DOM.mapStatus.textContent="Ruta trazada entre origen y destino."}catch{DOM.routeSummary.textContent="No se pudo calcular la ruta con esas ubicaciones."}}
function drawRoute(coordinates){const latLngs=coordinates.map(([lon,lat])=>[lat,lon]);if(state.routeLine){state.map.removeLayer(state.routeLine)}state.routeLine=L.polyline(latLngs,{weight:6,opacity:.95,color:"#6ea8ff"}).addTo(state.map);state.map.fitBounds(state.routeLine.getBounds(),{padding:[35,35]})}
function renderWallet(){const totalExpenses=state.expenses.reduce((sum,expense)=>sum+Number(expense.amount),0);const balance=state.salary-totalExpenses;const percent=state.salary>0?Math.min(totalExpenses/state.salary*100,100):0;DOM.salaryInput.value=state.salary?state.salary:"";DOM.incomeValue.textContent=formatCurrencyDOP(state.salary);DOM.expenseValue.textContent=formatCurrencyDOP(totalExpenses);DOM.balanceValue.textContent=formatCurrencyDOP(balance);DOM.budgetPercentLabel.textContent=`${Math.round(percent)}%`;DOM.budgetProgress.style.width=`${Math.max(0,Math.min(percent,100))}%`;DOM.heroWalletBalance.textContent=formatCurrencyDOP(balance);DOM.heroWalletText.textContent=balance<0?"Sobregirado":"Saldo disponible";if(state.salary<=0){DOM.walletStatusValue.textContent="Agrega tu sueldo"}else if(balance<0){DOM.walletStatusValue.textContent="Sobregirado"}else if(percent>=90){DOM.walletStatusValue.textContent="Muy ajustado"}else if(percent>=70){DOM.walletStatusValue.textContent="Cuidado"}else{DOM.walletStatusValue.textContent="Saludable"}if(!state.expenses.length){DOM.expensesList.innerHTML=`<div class="empty-state">Aún no has agregado gastos.</div>`;return}DOM.expensesList.innerHTML=state.expenses.map(expense=>`<article class="expense-item"><div class="expense-main"><strong>${escapeHtml(expense.title)}</strong><p>${escapeHtml(expense.category)} · ${formatNewsDate(expense.createdAt)}</p></div><div class="expense-right"><strong>${formatCurrencyDOP(expense.amount)}</strong><button class="delete-expense-btn" data-expense-id="${expense.id}">Eliminar</button></div></article>`).join("")}
function formatMoney(value){return new Intl.NumberFormat("es-DO",{minimumFractionDigits:2,maximumFractionDigits:2}).format(value)}
function formatCurrencyDOP(value){return new Intl.NumberFormat("es-DO",{style:"currency",currency:"DOP"}).format(Number(value||0))}
function formatNewsDate(value){if(!value)return"Fecha no disponible";const date=new Date(value);if(Number.isNaN(date.getTime()))return value;return new Intl.DateTimeFormat("es-DO",{day:"2-digit",month:"short",year:"numeric"}).format(date)}
function capitalize(text){return text?text.charAt(0).toUpperCase()+text.slice(1):""}
function escapeHtml(value){return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;")}
function cryptoRandomId(){return window.crypto&&crypto.randomUUID?crypto.randomUUID():`id-${Date.now()}-${Math.random().toString(16).slice(2)}`}
