const $=id=>document.getElementById(id);
const todayKey=()=>new Date().toISOString().slice(0,10);
const money=n=>new Intl.NumberFormat("es-DO",{style:"currency",currency:"DOP"}).format(Number(n)||0);
const timeFmt=d=>new Intl.DateTimeFormat("es-DO",{hour:"2-digit",minute:"2-digit"}).format(d instanceof Date?d:new Date(d));
const dateFmt=d=>new Intl.DateTimeFormat("es-DO",{weekday:"long",day:"2-digit",month:"long"}).format(d instanceof Date?d:new Date(d));
const safe=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));

const DOM={
  menuBtn:$("menuBtn"),mobileDrawer:$("mobileDrawer"),locateBtn:$("locateBtn"),drawerLocateBtn:$("drawerLocateBtn"),statusLabel:$("statusLabel"),locationLabel:$("locationLabel"),currentTime:$("currentTime"),lastUpdatedLabel:$("lastUpdatedLabel"),heroDayLabel:$("heroDayLabel"),heroTemp:$("heroTemp"),heroWeatherText:$("heroWeatherText"),heroRate:$("heroRate"),weatherTemp:$("weatherTemp"),weatherCondition:$("weatherCondition"),feelsLike:$("feelsLike"),windSpeed:$("windSpeed"),forecastStrip:$("forecastStrip"),usdToDop:$("usdToDop"),eurToDop:$("eurToDop"),exchangeUpdated:$("exchangeUpdated"),taskForm:$("taskForm"),taskInput:$("taskInput"),taskTime:$("taskTime"),taskPriority:$("taskPriority"),taskList:$("taskList"),pendingTasks:$("pendingTasks"),doneTasks:$("doneTasks"),taskProgressText:$("taskProgressText"),taskProgressBar:$("taskProgressBar"),clearDoneTasks:$("clearDoneTasks"),clearAllTasks:$("clearAllTasks"),heroTasksCount:$("heroTasksCount"),heroTasksText:$("heroTasksText"),newsQuery:$("newsQuery"),searchNewsBtn:$("searchNewsBtn"),newsList:$("newsList"),routeForm:$("routeForm"),destinationInput:$("destinationInput"),routeSummary:$("routeSummary"),startNavBtn:$("startNavBtn"),stopNavBtn:$("stopNavBtn"),navInstruction:$("navInstruction"),navRemaining:$("navRemaining"),navMode:$("navMode"),mapStatus:$("mapStatus"),incomeForm:$("incomeForm"),salaryInput:$("salaryInput"),incomeValue:$("incomeValue"),expenseValue:$("expenseValue"),balanceValue:$("balanceValue"),walletStatusValue:$("walletStatusValue"),budgetPercentLabel:$("budgetPercentLabel"),budgetProgress:$("budgetProgress"),expenseForm:$("expenseForm"),expenseName:$("expenseName"),expenseAmount:$("expenseAmount"),expenseList:$("expenseList"),heroWalletBalance:$("heroWalletBalance"),heroWalletText:$("heroWalletText")
};

const state={
  coords:JSON.parse(localStorage.getItem("brinow_coords")||"null")||{lat:18.4861,lon:-69.9312},
  locationName:localStorage.getItem("brinow_location_name")||"Santo Domingo, RD",
  map:null,userMarker:null,routeLine:null,destinationMarker:null,currentRoute:null,watchId:null,navigationActive:false,
  tasks:JSON.parse(localStorage.getItem(`brinow_tasks_${todayKey()}`)||"[]"),
  salary:Number(localStorage.getItem("brinow_salary")||0),
  expenses:JSON.parse(localStorage.getItem("brinow_expenses")||"[]")
};

function setStatus(text){if(DOM.statusLabel)DOM.statusLabel.textContent=text}
function saveCoords(lat,lon){state.coords={lat,lon};localStorage.setItem("brinow_coords",JSON.stringify(state.coords))}
function saveTasks(){localStorage.setItem(`brinow_tasks_${todayKey()}`,JSON.stringify(state.tasks))}
function saveWallet(){localStorage.setItem("brinow_salary",String(state.salary));localStorage.setItem("brinow_expenses",JSON.stringify(state.expenses))}

function tickClock(){const now=new Date();if(DOM.currentTime)DOM.currentTime.textContent=timeFmt(now);if(DOM.heroDayLabel)DOM.heroDayLabel.textContent=dateFmt(now)}

function initMenu(){
  const closeMenu=()=>{
    DOM.mobileDrawer?.classList.remove("open");
    DOM.menuBtn?.classList.remove("active");
    DOM.menuBtn?.setAttribute("aria-expanded","false");
  };
  const toggleMenu=()=>{
    const isOpen=DOM.mobileDrawer?.classList.toggle("open");
    DOM.menuBtn?.classList.toggle("active",!!isOpen);
    DOM.menuBtn?.setAttribute("aria-expanded",isOpen?"true":"false");
  };
  DOM.menuBtn?.addEventListener("click",toggleMenu);
  DOM.mobileDrawer?.querySelectorAll("a,button").forEach(el=>el.addEventListener("click",closeMenu));
  document.addEventListener("click",e=>{
    if(!DOM.mobileDrawer?.classList.contains("open"))return;
    if(DOM.mobileDrawer.contains(e.target)||DOM.menuBtn?.contains(e.target))return;
    closeMenu();
  });
  window.addEventListener("resize",()=>{if(window.innerWidth>1180)closeMenu()});
}

async function reverseGeocode(lat,lon){try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=json&accept-language=es&lat=${lat}&lon=${lon}`);if(!r.ok)throw new Error();const d=await r.json();const a=d.address||{};return [a.suburb||a.city||a.town||a.municipality,a.country_code?"RD":""].filter(Boolean).join(", ")||d.display_name||"Mi ubicación"}catch{return "Mi ubicación actual"}}

async function useMyLocation(){if(!navigator.geolocation){setStatus("GPS no disponible");return}setStatus("Buscando GPS");navigator.geolocation.getCurrentPosition(async p=>{const lat=p.coords.latitude,lon=p.coords.longitude;saveCoords(lat,lon);state.locationName=await reverseGeocode(lat,lon);localStorage.setItem("brinow_location_name",state.locationName);if(DOM.locationLabel)DOM.locationLabel.textContent=state.locationName;updateMapPosition(lat,lon,state.locationName);await loadWeather();setStatus("Ubicación lista")},()=>setStatus("GPS denegado"),{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}

async function loadWeather(){try{setStatus("Clima");const {lat,lon}=state.coords;const url=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&hourly=temperature_2m,weather_code&forecast_days=1&timezone=auto`;const r=await fetch(url);if(!r.ok)throw new Error();const d=await r.json();const c=d.current||{};const temp=Math.round(c.temperature_2m);const cond=weatherText(c.weather_code);DOM.heroTemp.textContent=`${temp}°`;DOM.heroWeatherText.textContent=cond;DOM.weatherTemp.textContent=`${temp}°C`;DOM.weatherCondition.textContent=cond;DOM.feelsLike.textContent=`${Math.round(c.apparent_temperature)}°C`;DOM.windSpeed.textContent=`${Math.round(c.wind_speed_10m)} km/h`;renderForecast(d.hourly);markUpdated();setStatus("Listo")}catch{DOM.weatherCondition.textContent="No se pudo cargar el clima";setStatus("Clima falló")}}

function weatherText(code){const map={0:"Cielo despejado",1:"Principalmente despejado",2:"Parcialmente nublado",3:"Nublado",45:"Neblina",48:"Neblina con escarcha",51:"Llovizna ligera",53:"Llovizna",55:"Llovizna intensa",61:"Lluvia ligera",63:"Lluvia",65:"Lluvia fuerte",80:"Chubascos",81:"Chubascos moderados",82:"Chubascos fuertes",95:"Tormenta"};return map[code]||"Condición variable"}
function renderForecast(hourly){if(!DOM.forecastStrip||!hourly?.time)return;const now=new Date();const items=hourly.time.map((t,i)=>({t:new Date(t),temp:hourly.temperature_2m[i],code:hourly.weather_code[i]})).filter(x=>x.t>=now).slice(0,4);DOM.forecastStrip.innerHTML=items.map(x=>`<div class="forecast-item"><span>${timeFmt(x.t)}</span><strong>${Math.round(x.temp)}°</strong><small>${safe(weatherText(x.code))}</small></div>`).join("")||`<p class="empty">Sin pronóstico disponible.</p>`}

async function loadExchange(){try{const r=await fetch("https://open.er-api.com/v6/latest/USD");if(!r.ok)throw new Error();const d=await r.json();const usd=d.rates?.DOP;const eur=usd/(d.rates?.EUR||1);DOM.usdToDop.textContent=usd?`RD$ ${usd.toFixed(2)}`:"--";DOM.eurToDop.textContent=eur?`RD$ ${eur.toFixed(2)}`:"--";DOM.heroRate.textContent=usd?usd.toFixed(2):"--";DOM.exchangeUpdated.textContent=timeFmt(new Date());markUpdated()}catch{DOM.exchangeUpdated.textContent="No disponible"}}

async function loadDailyNews(force=false){const query=(DOM.newsQuery?.value.trim()||"República Dominicana");const cacheKey=`brinow_daily_news_${todayKey()}_${query.toLowerCase()}`;const cached=JSON.parse(localStorage.getItem(cacheKey)||"null");if(cached&&!force){renderNews(cached);return}try{setStatus("Noticias");const rss=`https://news.google.com/rss/search?q=${encodeURIComponent(query)}&hl=es-419&gl=DO&ceid=DO:es-419`;let article=null;try{const r=await fetch(`https://api.rss2json.com/v1/api.json?rss_url=${encodeURIComponent(rss)}`);if(r.ok){const d=await r.json();const item=d.items?.[0];if(item)article={title:item.title,link:item.link,source:item.author||"Google News",date:item.pubDate,description:item.description?.replace(/<[^>]+>/g,"").slice(0,180)||"Noticia destacada del día."}}}catch{}if(!article){const r=await fetch(`https://api.allorigins.win/raw?url=${encodeURIComponent(rss)}`);if(!r.ok)throw new Error();const xml=await r.text();const doc=new DOMParser().parseFromString(xml,"text/xml");const item=doc.querySelector("item");if(item)article={title:item.querySelector("title")?.textContent||"Noticia del día",link:item.querySelector("link")?.textContent||"#",source:item.querySelector("source")?.textContent||"Google News",date:item.querySelector("pubDate")?.textContent||new Date().toISOString(),description:"Resumen disponible desde Google News RSS."}}
    if(!article)throw new Error();localStorage.setItem(cacheKey,JSON.stringify(article));renderNews(article);setStatus("Listo")}catch{renderNews({title:"No se pudo cargar la noticia automática",link:"https://news.google.com/",source:"Google News",date:new Date().toISOString(),description:"La app queda preparada con RSS gratuito y caché diaria. Intenta actualizar más tarde."});setStatus("Noticias falló")}}
function renderNews(a){DOM.newsList.innerHTML=`<article class="news-item"><h3>${safe(a.title)}</h3><p>${safe(a.description||"Noticia destacada del día.")}</p><p>${safe(a.source||"Fuente")} · ${safe(timeFmt(a.date||new Date()))}</p><a href="${safe(a.link||"#")}" target="_blank" rel="noopener noreferrer">Ver noticia</a></article>`}

function renderTasks(){const total=state.tasks.length,done=state.tasks.filter(t=>t.done).length,pending=total-done,percent=total?Math.round(done/total*100):0;DOM.pendingTasks.textContent=pending;DOM.doneTasks.textContent=done;DOM.taskProgressText.textContent=`${percent}%`;DOM.taskProgressBar.style.width=`${percent}%`;DOM.heroTasksCount.textContent=`${done}/${total}`;DOM.heroTasksText.textContent=total?`${pending} pendientes`:"Sin tareas";if(!total){DOM.taskList.innerHTML=`<p class="empty">Aún no tienes tareas para hoy.</p>`;return}DOM.taskList.innerHTML=state.tasks.sort((a,b)=>(a.done-b.done)||String(a.time||"99:99").localeCompare(String(b.time||"99:99"))).map(t=>`<article class="task-item ${t.done?"done":""}"><input class="task-check" type="checkbox" data-id="${t.id}" ${t.done?"checked":""}><div><div class="task-title">${safe(t.title)}</div><div class="task-meta"><span>${safe(t.time||"Sin hora")}</span> · <span class="priority-${safe(t.priority)}">${safe(t.priority)}</span></div></div><button class="task-delete" data-delete="${t.id}">Eliminar</button></article>`).join("")}
function addTask(e){e.preventDefault();const title=DOM.taskInput.value.trim();if(!title)return;state.tasks.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),title,time:DOM.taskTime.value,priority:DOM.taskPriority.value,done:false,createdAt:new Date().toISOString()});DOM.taskForm.reset();saveTasks();renderTasks()}
function handleTaskClick(e){const id=e.target.dataset.id||e.target.dataset.delete;if(!id)return;if(e.target.dataset.delete){state.tasks=state.tasks.filter(t=>t.id!==id)}else{state.tasks=state.tasks.map(t=>t.id===id?{...t,done:e.target.checked}:t)}saveTasks();renderTasks()}

function renderWallet(){const expenses=state.expenses.reduce((s,x)=>s+Number(x.amount||0),0);const balance=state.salary-expenses;const percent=state.salary?Math.min(100,Math.round(expenses/state.salary*100)):0;DOM.incomeValue.textContent=money(state.salary);DOM.expenseValue.textContent=money(expenses);DOM.balanceValue.textContent=money(balance);DOM.heroWalletBalance.textContent=money(balance);DOM.heroWalletText.textContent=balance>=0?"Disponible":"Sobrepasado";DOM.walletStatusValue.textContent=!state.salary?"Sin datos":balance>=0?"Estable":"Excedido";DOM.budgetPercentLabel.textContent=`${percent}%`;DOM.budgetProgress.style.width=`${percent}%`;DOM.salaryInput.value=state.salary||"";DOM.expenseList.innerHTML=state.expenses.length?state.expenses.map(x=>`<article class="expense-item"><div><strong>${safe(x.name)}</strong><span>${safe(new Date(x.date).toLocaleDateString("es-DO"))}</span></div><strong>${money(x.amount)}</strong><button class="expense-delete" data-expense="${x.id}">Eliminar</button></article>`).join(""):`<p class="empty">No hay gastos registrados.</p>`}
function saveIncome(e){e.preventDefault();state.salary=Number(DOM.salaryInput.value||0);saveWallet();renderWallet()}
function addExpense(e){e.preventDefault();const name=DOM.expenseName.value.trim();const amount=Number(DOM.expenseAmount.value||0);if(!name||amount<=0)return;state.expenses.unshift({id:String(Date.now()),name,amount,date:new Date().toISOString()});DOM.expenseForm.reset();saveWallet();renderWallet()}
function deleteExpense(e){const id=e.target.dataset.expense;if(!id)return;state.expenses=state.expenses.filter(x=>x.id!==id);saveWallet();renderWallet()}

function initMap(){if(typeof L==="undefined"||!$("map"))return;const {lat,lon}=state.coords;state.map=L.map("map",{zoomControl:true}).setView([lat,lon],12);L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{attribution:"&copy; OpenStreetMap &copy; CARTO"}).addTo(state.map);state.userMarker=L.marker([lat,lon]).addTo(state.map).bindPopup(`<strong>${safe(state.locationName)}</strong>`)}
function updateMapPosition(lat,lon,label){if(!state.map)return;state.map.setView([lat,lon],state.navigationActive?17:12);state.userMarker?.setLatLng([lat,lon]).bindPopup(`<strong>${safe(label)}</strong>`);DOM.mapStatus.textContent=`Vista centrada en ${label}.`}
async function geocodeLocation(query){const urls=[`https://nominatim.openstreetmap.org/search?format=json&limit=1&accept-language=es&countrycodes=do&q=${encodeURIComponent(query)}`,`https://nominatim.openstreetmap.org/search?format=json&limit=1&accept-language=es&q=${encodeURIComponent(query)}`];for(const url of urls){const r=await fetch(url);if(!r.ok)continue;const d=await r.json();if(d?.length)return{lat:Number(d[0].lat),lon:Number(d[0].lon),name:d[0].display_name}}throw new Error("Destino no encontrado")}
async function calculateRoute(e){e?.preventDefault();const q=DOM.destinationInput.value.trim();if(!q){DOM.routeSummary.textContent="Escribe un destino";return}try{DOM.routeSummary.textContent="Calculando ruta...";const dest=await geocodeLocation(q);const {lat,lon}=state.coords;const url=`https://router.project-osrm.org/route/v1/driving/${lon},${lat};${dest.lon},${dest.lat}?overview=full&geometries=geojson&steps=true`;const r=await fetch(url);if(!r.ok)throw new Error("Servidor de rutas no disponible");const d=await r.json();const route=d.routes?.[0];if(!route)throw new Error("No hay ruta disponible");state.currentRoute={distance:route.distance,duration:route.duration,geometry:route.geometry.coordinates,steps:route.legs?.[0]?.steps||[],destination:dest};drawRoute(route.geometry.coordinates,dest);DOM.routeSummary.textContent=`${(route.distance/1000).toFixed(1)} km · ${Math.round(route.duration/60)} min`;DOM.navInstruction.textContent=buildInstruction(state.currentRoute.steps[0]);DOM.navRemaining.textContent=`${(route.distance/1000).toFixed(1)} km`;DOM.navMode.textContent="Ruta lista"}catch(err){DOM.routeSummary.textContent=err.message||"No se pudo calcular la ruta";DOM.navMode.textContent="Error"}}
function drawRoute(coords,dest){if(!state.map)return;const latLngs=coords.map(([lon,lat])=>[lat,lon]);if(state.routeLine)state.map.removeLayer(state.routeLine);if(state.destinationMarker)state.map.removeLayer(state.destinationMarker);state.routeLine=L.polyline(latLngs,{weight:6,opacity:.95,color:"#d4af37"}).addTo(state.map);state.destinationMarker=L.marker([dest.lat,dest.lon]).addTo(state.map).bindPopup(`<strong>${safe(dest.name)}</strong>`);state.map.fitBounds(state.routeLine.getBounds(),{padding:[38,38]});DOM.mapStatus.textContent="Ruta calculada correctamente"}
function buildInstruction(step){if(!step)return"Sigue la ruta marcada";const type=step.maneuver?.type||"continue",mod=step.maneuver?.modifier||"",road=step.name?` por ${step.name}`:"";const base={depart:"Sal",turn:"Gira",continue:"Sigue recto",arrive:"Llegaste",merge:"Incorpórate",roundabout:"Entra a la rotonda"}[type]||"Continúa";const side={left:" a la izquierda",right:" a la derecha",straight:" recto",slight_left:" levemente a la izquierda",slight_right:" levemente a la derecha"}[mod]||"";return `${base}${side}${road}`}
function startNavigation(){if(!state.currentRoute){DOM.navInstruction.textContent="Calcula una ruta primero";DOM.navMode.textContent="Sin ruta";return}if(!navigator.geolocation){DOM.navMode.textContent="GPS no disponible";return}stopNavigation(false);state.navigationActive=true;DOM.navMode.textContent="Navegando";state.watchId=navigator.geolocation.watchPosition(p=>{const lat=p.coords.latitude,lon=p.coords.longitude;saveCoords(lat,lon);updateMapPosition(lat,lon,"Mi ubicación actual");updateNavigationProgress(lat,lon)},()=>{DOM.navMode.textContent="Error GPS"},{enableHighAccuracy:true,maximumAge:1000,timeout:10000})}
function stopNavigation(update=true){if(state.watchId!==null){navigator.geolocation.clearWatch(state.watchId);state.watchId=null}state.navigationActive=false;if(update){DOM.navMode.textContent="Inactivo";DOM.navInstruction.textContent="Navegación detenida"}}
function updateNavigationProgress(lat,lon){if(!state.currentRoute)return;const dest=state.currentRoute.destination;const remaining=distanceBetween(lat,lon,dest.lat,dest.lon);DOM.navRemaining.textContent=remaining>=1000?`${(remaining/1000).toFixed(1)} km`:`${Math.round(remaining)} m`;if(remaining<45){DOM.navInstruction.textContent="Has llegado al destino";DOM.navMode.textContent="Llegaste";stopNavigation(false)}else{DOM.navInstruction.textContent=buildInstruction(state.currentRoute.steps[0])}}
function distanceBetween(lat1,lon1,lat2,lon2){const R=6371000,toRad=x=>x*Math.PI/180;const dLat=toRad(lat2-lat1),dLon=toRad(lon2-lon1);const a=Math.sin(dLat/2)**2+Math.cos(toRad(lat1))*Math.cos(toRad(lat2))*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}
function markUpdated(){const now=new Date();DOM.lastUpdatedLabel.textContent=timeFmt(now)}

function bindEvents(){DOM.locateBtn?.addEventListener("click",useMyLocation);DOM.drawerLocateBtn?.addEventListener("click",useMyLocation);DOM.taskForm?.addEventListener("submit",addTask);DOM.taskList?.addEventListener("click",handleTaskClick);DOM.clearDoneTasks?.addEventListener("click",()=>{state.tasks=state.tasks.filter(t=>!t.done);saveTasks();renderTasks()});DOM.clearAllTasks?.addEventListener("click",()=>{state.tasks=[];saveTasks();renderTasks()});DOM.searchNewsBtn?.addEventListener("click",()=>loadDailyNews(true));DOM.routeForm?.addEventListener("submit",calculateRoute);DOM.startNavBtn?.addEventListener("click",startNavigation);DOM.stopNavBtn?.addEventListener("click",()=>stopNavigation(true));DOM.incomeForm?.addEventListener("submit",saveIncome);DOM.expenseForm?.addEventListener("submit",addExpense);DOM.expenseList?.addEventListener("click",deleteExpense)}

async function init(){initMenu();bindEvents();tickClock();setInterval(tickClock,1000);if(DOM.locationLabel)DOM.locationLabel.textContent=state.locationName;initMap();renderTasks();renderWallet();await Promise.allSettled([loadWeather(),loadExchange(),loadDailyNews(false)]);setStatus("Listo")}

document.addEventListener("DOMContentLoaded",init);
